// The logs query assembles its WHERE clause as text, so this guards the one
// property that makes that safe: user values only ever reach SQL through the
// parameter array, never through the query string.
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";

const QUERIES = readFileSync(join(process.cwd(), "lib", "queries.ts"), "utf8");
const WORKER_DB = readFileSync(
  join(process.cwd(), "worker", "src", "db.ts"),
  "utf8",
);

describe("SQL safety", () => {
  it("the logs builder never concatenates a user value into SQL text", () => {
    // Everything user-supplied goes through add(), which pushes to `values`
    // and returns a $n placeholder. Catch a direct interpolation of any
    // request field into a SQL string.
    // `where ${where.join(" and ")}` is deliberate and safe: those fragments
    // are generated by the builder and contain only $n placeholders. What
    // must never appear is a *request field* inside a template literal.
    const dangerous = [
      /\$\{q\.agent\}/,
      /\$\{q\.services/,
      /\$\{q\.outcome\}/,
      /\$\{q\.cursor\.(checkedAt|serviceId|agent)\}/,
      /\$\{q\.from\}/,
      /\$\{q\.to\}/,
    ];
    for (const pattern of dangerous) {
      expect(QUERIES, `interpolation matching ${pattern}`).not.toMatch(pattern);
    }
  });

  it("every where-fragment pushed by the builder carries a placeholder, not a value", () => {
    // Each `where.push(...)` line must either be a constant predicate or use
    // a ${...} that resolves to a $n placeholder from add().
    const pushes = [...QUERIES.matchAll(/where\.push\(([\s\S]*?)\);\n/g)].map(
      (m) => m[1],
    );
    expect(pushes.length).toBeGreaterThan(4);

    for (const fragment of pushes) {
      const interpolations = [...fragment.matchAll(/\$\{([^}]+)\}/g)].map(
        (m) => m[1].trim(),
      );
      for (const expr of interpolations) {
        // Allowed: add(...) calls and the params they were stored in.
        const safe =
          expr.startsWith("add(") ||
          /^(idsParam|valuesParam)$/.test(expr);
        expect(safe, `where-fragment interpolates ${expr}`).toBe(true);
      }
    }
  });

  it("only the row limit and generated placeholders shape the query text", () => {
    // `add()` returns "$n"; the builder must use it for every value.
    expect(QUERIES).toMatch(/const add = \(value: unknown\): string => \{/);
    expect(QUERIES).toMatch(/values\.push\(value\);/);
    expect(QUERIES).toMatch(/return `\$\$\{values\.length\}`;/);
  });

  it("the worker's writes use tagged templates, which parameterise by construction", () => {
    // A raw sql.query( call in the writer would bypass the tagged template's
    // parameterisation, so there should be none.
    expect(WORKER_DB).not.toMatch(/sql\.query\(/);
  });

  it("no query string is built by joining user input with quotes", () => {
    for (const source of [QUERIES, WORKER_DB]) {
      expect(source).not.toMatch(/'\s*\+\s*\w/);
      expect(source).not.toMatch(/\+\s*"'"/);
    }
  });
});
